### ISSUE TITLE
Incompatible with rails 5.1 (foreman >= 1.18)

### ISSUE THREAD

**Issue by alexjfisher** [joshuabaird/foreman_noenv#20]
After upgrading to 1.18, I noticed this in the logs
```
ForemanNoenv: skipping engine hook (undefined method `alias_method_chain'
```

`alias_method_chain` was [removed](
https://www.justinweiss.com/articles/the-lesser-known-features-in-rails-5-dot-1/) in rails 5.1.

It appears in the code [here](
https://github.com/joshuabaird/foreman_noenv/blob/97d6ae27c358be4d607fdc6c97eb4d8560213f31/app/models/concerns/foreman_noenv/host_managed_extensions.rb#L6)

This [blog](
https://littlelines.com/blog/2018/01/31/replace-alias-method-chain) post could be helpful to anyone who wants to code a fix.
